# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-08 03:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GDNN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('pub_date', models.DateField(blank=True, null=True, verbose_name='Ngày')),
                ('Vol_Mua', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Mua')),
                ('Val_Mua', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Mua')),
                ('Vol_Ban', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Bán')),
                ('Val_Ban', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Bán')),
                ('Vol_Rong', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KLGD Ròng')),
                ('Val_Rong', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GTGD Ròng')),
                ('Vol_Mua_KL', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Mua Khớp Lệnh')),
                ('Val_Mua_KL', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Mua Khớp Lệnh')),
                ('Vol_Ban_KL', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Bán Khớp Lệnh')),
                ('Val_Ban_KL', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Bán Khớp Lệnh')),
                ('Val_KL_Rong', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GTGD Khớp Lệnh Ròng')),
                ('Vol_Mua_TT', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Mua TT')),
                ('Val_Mua_TT', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Mua TT')),
                ('Vol_Ban_TT', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='KL Bán TT')),
                ('Val_Ban_TT', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GT Bán TT')),
                ('Val_TT_Rong', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='GTGD TT Ròng')),
                ('Room_NN_hientai', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Room NN hiện tại')),
                ('Total_Room_NN', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Tổng Room NN')),
                ('Phantram_tong_SH_NN', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tổng phần trăm room NN')),
                ('SH_NN', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='Tổng SH NN')),
                ('Phantram_SH_NN', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tổng phần trăm SH NN')),
            ],
            options={
                'ordering': ('-pub_date',),
            },
        ),
        migrations.CreateModel(
            name='Viewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_gdnn', models.BigIntegerField(default=0)),
            ],
        ),
    ]
