# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-08 03:08
from __future__ import unicode_literals

import datetime
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Viewed',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_list_Vimo', models.BigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vimo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateField(default=datetime.date.today)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10)),
                ('Tenthongtin', models.CharField(max_length=200)),
                ('Anhhuong', models.IntegerField(choices=[(0, 'Xấu'), (1, 'Tốt'), (2, 'Chưa XĐ')], default=2)),
                ('Nhanxet', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Nhận xét')),
                ('Mucdo', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('CP_anhhuong', models.CharField(max_length=200)),
                ('DangAH', models.IntegerField(choices=[(0, 'Hết AH'), (1, 'Còn AH')], default=1)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Vimo', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
