# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myprofile',
            name='user',
        ),
        migrations.DeleteModel(
            name='MyProfile',
        ),
    ]
