# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 18:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0003_myprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=12, null=True, verbose_name='Số Điện thoại'),
        ),
    ]
