# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-20 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0004_myprofile_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='myprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AddField(
            model_name='myprofile',
            name='contact_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Số Điện thoại'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày sinh'),
        ),
    ]
