# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-21 04:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0008_auto_20190421_0517'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='clientprofile', to=settings.AUTH_USER_MODEL),
        ),
    ]
