# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-25 07:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Pages', '0009_auto_20190421_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='myprofile',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars', verbose_name='Ảnh đại diện'),
        ),
        migrations.AlterField(
            model_name='myprofile',
            name='contact_address',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Địa chỉ liên lạc'),
        ),
    ]
