# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-13 09:30
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import mezzanine.core.fields
import mezzanine.utils.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sites', '0002_alter_domain_unique'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Estimate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('publish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('close_date', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('S_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('S_updated', models.DateTimeField(auto_now=True, null=True)),
                ('S_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, null=True)),
                ('Postion', models.CharField(blank=True, choices=[('Mở vị thế', 'Mở vị thế'), ('Đóng vị thế', 'Đóng vị thế')], max_length=20, null=True)),
                ('Style', models.CharField(blank=True, choices=[('Dài hạn', 'Dài hạn'), ('Ngắn hạn', 'Ngắn hạn')], max_length=10, null=True)),
                ('Price_open', models.IntegerField(default=1, verbose_name='Giá mở vị thế')),
                ('Price_close', models.IntegerField(blank=True, default=1, null=True, verbose_name='Giá đóng vị thế')),
                ('EPS', models.IntegerField(blank=True, null=True, verbose_name='EPS')),
                ('Bookvalue', models.IntegerField(blank=True, null=True, verbose_name='Book Value')),
                ('Liquidity_30days', models.BigIntegerField(blank=True, null=True, verbose_name='KL GDTB 30 ngày')),
                ('Price_change_5days', models.IntegerField(blank=True, null=True, verbose_name='Giá thay đổi 5 ngày')),
                ('Price_change_20days', models.IntegerField(blank=True, null=True, verbose_name='Giá thay đổi 20 ngày')),
                ('Price_change_60days', models.IntegerField(blank=True, null=True, verbose_name='Giá thay đổi 60 ngày')),
                ('EnvironmentIndustry', models.IntegerField(default=50, help_text='0-10', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Môi trường kinh doanh')),
                ('W_Envi', models.PositiveIntegerField(default=20, help_text='mặc định chuẩn, có thể thay đổi khi cần thiết', verbose_name='Tỷ trọng')),
                ('Management', models.IntegerField(default=50, help_text='0-10', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Quản trị Doanh Nghiệp')),
                ('W_Ma', models.IntegerField(default=10, help_text='mặc định chuẩn, có thể thay đổi khi cần thiết', verbose_name='Tỷ trọng')),
                ('Qualify_asset', models.IntegerField(default=50, help_text='0-10', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Chất lượng tài sản')),
                ('W_Qu_As', models.PositiveIntegerField(default=10, help_text='mặc định chuẩn, có thể thay đổi khi cần thiết', verbose_name='Tỷ trọng')),
                ('Leverage', models.IntegerField(default=50, help_text='0-10', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Tỷ lệ vay nợ')),
                ('W_Lev', models.PositiveIntegerField(default=10, help_text='mặc định chuẩn, có thể thay đổi khi cần thiết', verbose_name='Tỷ trọng')),
                ('Top_industry', models.IntegerField(default=50, help_text='0-10', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Khả năng gây ảnh hưởng trong ngành')),
                ('W_Top_industry', models.PositiveIntegerField(default=10, help_text='mặc định chuẩn, có thể thay đổi khi cần thiết', verbose_name='Tỷ trọng')),
                ('Perform', models.IntegerField(default=50, help_text='0-10', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Hiệu suất kinh doanh')),
                ('W_Perform', models.PositiveIntegerField(default=15, help_text='mặc định chuẩn, có thể thay đổi khi cần thiết', verbose_name='Tỷ trọng')),
                ('Capital', models.IntegerField(default=50, help_text='0-10', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Vốn hóa')),
                ('W_Ca', models.IntegerField(default=10, help_text='mặc định chuẩn, có thể thay đổi khi cần thiết', verbose_name='Tỷ trọng')),
                ('Liquidity', models.IntegerField(default=50, help_text='0-10', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Thanh khoản')),
                ('W_Li', models.IntegerField(default=15, help_text='mặc định chuẩn, có thể thay đổi khi cần thiết', verbose_name='Tỷ trọng')),
                ('Commnent', models.TextField(blank=True, help_text='mặc định chuẩn, có thể thay đổi khi cần thiết', max_length=2000, null=True, verbose_name='Đánh giá DN')),
                ('action', models.TextField(blank=True, help_text='Cho nhận xét về DN', max_length=2000, null=True, verbose_name='Nhận xét')),
                ('Risk', models.IntegerField(default=50, help_text='0-100', validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Rủi ro')),
                ('estimate_url', models.URLField(blank=True, help_text='đường dẫn youtube hoặc url khác', max_length=500, null=True, verbose_name='URL')),
                ('Title', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='title')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='NganhdandatTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nganh', models.CharField(max_length=200, verbose_name='Ngành')),
                ('Mucdo', models.IntegerField(blank=True, default=0, help_text='0-100', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Độ mạnh')),
                ('CP_noibat', models.CharField(max_length=200)),
                ('Mau', models.CharField(blank=True, choices=[('red', 'Đỏ'), ('yellow', 'Vàng'), ('green', 'Xanh lá'), ('blue', 'Xanh da trời')], max_length=10, null=True, verbose_name='Màu')),
            ],
        ),
        migrations.CreateModel(
            name='Recommend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments_count', models.IntegerField(default=0, editable=False)),
                ('keywords_string', models.CharField(blank=True, editable=False, max_length=500)),
                ('rating_count', models.IntegerField(default=0, editable=False)),
                ('rating_sum', models.IntegerField(default=0, editable=False)),
                ('rating_average', models.FloatField(default=0, editable=False)),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL')),
                ('_meta_title', models.CharField(blank=True, help_text='Optional title to be used in the HTML title tag. If left blank, the main title field will be used.', max_length=500, null=True, verbose_name='Title')),
                ('description', models.TextField(blank=True, verbose_name='Description')),
                ('gen_description', models.BooleanField(default=True, help_text='If checked, the description will be automatically generated from content. Uncheck if you want to manually set a custom description.', verbose_name='Generate description')),
                ('created', models.DateTimeField(editable=False, null=True)),
                ('updated', models.DateTimeField(editable=False, null=True)),
                ('status', models.IntegerField(choices=[(1, 'Draft'), (2, 'Published')], default=2, help_text='With Draft chosen, will only be shown for admin users on the site.', verbose_name='Status')),
                ('publish_date', models.DateTimeField(blank=True, db_index=True, help_text="With Published chosen, won't be shown until this time", null=True, verbose_name='Published from')),
                ('expiry_date', models.DateTimeField(blank=True, help_text="With Published chosen, won't be shown after this time", null=True, verbose_name='Expires on')),
                ('short_url', models.URLField(blank=True, null=True)),
                ('in_sitemap', models.BooleanField(default=True, verbose_name='Show in sitemap')),
                ('content', mezzanine.core.fields.RichTextField(verbose_name='Content')),
                ('Streng', models.IntegerField(blank=True, help_text='0-100', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Độ mạnh')),
                ('allow_comments', models.BooleanField(default=True, verbose_name='Allow comments')),
                ('viewed', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Recommend',
                'verbose_name_plural': 'Recommends',
                'ordering': ('-publish_date',),
            },
            bases=(models.Model, mezzanine.utils.models.AdminThumbMixin),
        ),
        migrations.CreateModel(
            name='Recommend_Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500, verbose_name='Title')),
                ('slug', models.CharField(blank=True, help_text='Leave blank to have the URL auto-generated from the title.', max_length=2000, verbose_name='URL')),
                ('site', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site')),
            ],
            options={
                'verbose_name': 'Recommend Category',
                'verbose_name_plural': 'Recommend Categories',
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='Stock_Detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('S_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('S_updated', models.DateTimeField(auto_now=True, null=True)),
                ('S_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, null=True)),
                ('Symbol', models.CharField(blank=True, max_length=10, null=True, unique=True, verbose_name='Mã CK')),
                ('Name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Tên Công Ty')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, null=True, populate_from='Symbol')),
                ('San', models.CharField(blank=True, max_length=10, null=True, verbose_name='Sàn')),
                ('Website', models.CharField(blank=True, max_length=100, null=True, verbose_name='Website')),
                ('So_dien_thoai', models.CharField(blank=True, max_length=50, null=True, verbose_name='Số điện thoại')),
                ('Dia_chi', models.CharField(blank=True, max_length=200, null=True, verbose_name='Địa chỉ')),
                ('Quan', models.CharField(blank=True, max_length=50, null=True, verbose_name='Quận/Huyện')),
                ('Tinh', models.CharField(blank=True, max_length=100, null=True, verbose_name='Tỉnh/Thành')),
                ('Tong_Quan', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Tổng quan')),
                ('Industry', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ngành')),
                ('SL_CP_Niem_yet', models.BigIntegerField(blank=True, null=True, verbose_name='Số lượng CP Niêm Yết')),
                ('Ty_le_Freeloat', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Free-loat')),
                ('Ty_le_SHNN', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='Tỷ lệ SH NN tối đa')),
                ('viewed', models.IntegerField(blank=True, default=0, null=True)),
            ],
            options={
                'ordering': ('Symbol',),
            },
        ),
        migrations.CreateModel(
            name='Update_Trade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=250, null=True)),
                ('publish', models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('S_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('S_updated', models.DateTimeField(auto_now=True, null=True)),
                ('S_status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='draft', max_length=10, null=True)),
                ('Trade', models.CharField(blank=True, choices=[('Mua mới', 'Mua mới'), ('Mua thêm', 'Mua thêm'), ('Nắm  giữ', 'Nắm  giữ'), ('Chốt lời', 'Chốt lời'), ('Cắt lỗ', 'Cắt lỗ'), ('Bán bớt', 'Bán bớt'), ('Bán hết', 'Bán hết')], max_length=10, null=True)),
                ('Price_update', models.IntegerField(default=1, verbose_name='Giá cập nhật')),
                ('Indicator', models.IntegerField(default=50, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)])),
                ('action', models.TextField(blank=True, max_length=2000, null=True, verbose_name='Đề xuất GD')),
                ('DateRecommend', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='DexuatGD.Recommend')),
                ('Stock', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='update_trade', to='DexuatGD.Estimate')),
            ],
            options={
                'ordering': ('publish',),
            },
        ),
        migrations.CreateModel(
            name='view_tonghopTT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_tonghop', models.BigIntegerField(blank=True, default=0, null=True, verbose_name='lượt xem trang TH')),
            ],
        ),
        migrations.AddField(
            model_name='recommend',
            name='Stock_chosen',
            field=models.ManyToManyField(blank=True, related_name='Recommend', through='DexuatGD.Update_Trade', to='DexuatGD.Estimate', verbose_name='Chọn CP'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='categories',
            field=models.ManyToManyField(blank=True, related_name='Recommends', to='DexuatGD.Recommend_Category'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='related_posts',
            field=models.ManyToManyField(blank=True, related_name='_recommend_related_posts_+', to='DexuatGD.Recommend', verbose_name='Related posts'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='site',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='sites.Site'),
        ),
        migrations.AddField(
            model_name='recommend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommends', to=settings.AUTH_USER_MODEL, verbose_name='Author'),
        ),
        migrations.AddField(
            model_name='nganhdandattt',
            name='NgayRecommend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='DexuatGD.Recommend'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='Stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='estimate_Com', to='DexuatGD.Stock_Detail'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to=settings.AUTH_USER_MODEL),
        ),
    ]
