# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 04:41
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estimate',
            name='Bookvalue',
        ),
        migrations.RemoveField(
            model_name='estimate',
            name='EPS',
        ),
        migrations.AddField(
            model_name='recommend',
            name='Risk',
            field=models.IntegerField(blank=True, help_text='0-100', null=True, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Rủi ro'),
        ),
        migrations.AlterField(
            model_name='stock_detail',
            name='S_status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published')], default='published', max_length=10, null=True),
        ),
    ]
