# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-21 04:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0002_auto_20190621_1141'),
    ]

    operations = [
        migrations.AddField(
            model_name='estimate',
            name='Bookvalue',
            field=models.IntegerField(blank=True, null=True, verbose_name='Book Value'),
        ),
        migrations.AddField(
            model_name='estimate',
            name='EPS',
            field=models.IntegerField(blank=True, null=True, verbose_name='EPS'),
        ),
    ]
