# -*- coding: utf-8 -*-
# Generated by Django 1.11.21 on 2019-06-22 08:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DexuatGD', '0003_auto_20190621_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommend',
            name='Recommend_url',
            field=models.URLField(blank=True, help_text='đường dẫn youtube hoặc url khác', max_length=500, null=True, verbose_name='URL'),
        ),
    ]
